'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { formatMoney } from '@/lib/format';
import type { SellerPayout } from '@/lib/types';

export default function SellerPayoutsPage() {
  const [payouts, setPayouts] = useState<SellerPayout[] | null>(null);

  useEffect(() => {
    api<SellerPayout[]>('/payouts/mine').then(setPayouts).catch(() => setPayouts([]));
  }, []);

  return (
    <div>
      <h1 className="font-heading text-2xl font-bold text-espresso-800">Payouts</h1>
      <p className="mt-1 text-sm text-espresso-500">
        Payouts are generated by iCoffeeHub admin at the end of each settlement period, after commission is deducted.
      </p>

      {!payouts ? (
        <p className="mt-4 text-sm text-espresso-400">Loading…</p>
      ) : payouts.length === 0 ? (
        <p className="mt-4 text-sm text-espresso-500">No payouts generated yet.</p>
      ) : (
        <div className="mt-5 overflow-x-auto rounded-xl2 border border-espresso-100">
          <table className="w-full text-left text-sm">
            <thead className="bg-cream-100 text-xs uppercase tracking-wide text-espresso-500">
              <tr>
                <th className="px-4 py-3">Period</th>
                <th className="px-4 py-3">Gross Sales</th>
                <th className="px-4 py-3">Commission</th>
                <th className="px-4 py-3">Net Payout</th>
                <th className="px-4 py-3">Status</th>
              </tr>
            </thead>
            <tbody>
              {payouts.map((p) => (
                <tr key={p._id} className="border-t border-espresso-100">
                  <td className="px-4 py-3 text-espresso-700">
                    {new Date(p.periodStart).toLocaleDateString()} – {new Date(p.periodEnd).toLocaleDateString()}
                  </td>
                  <td className="px-4 py-3 text-espresso-600">{formatMoney(p.grossSales)}</td>
                  <td className="px-4 py-3 text-espresso-600">{formatMoney(p.commissionAmount)} ({p.commissionRate}%)</td>
                  <td className="px-4 py-3 font-semibold text-espresso-800">{formatMoney(p.netPayout)}</td>
                  <td className="px-4 py-3">
                    <span className={`badge ${p.status === 'paid' ? 'bg-forest-50 text-forest-700' : 'bg-gold-50 text-gold-700'}`}>{p.status}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
